services:
    anime_db.smotret_anime.browser:
        class: AnimeDb\Bundle\SmotretAnimeBrowserBundle\Service\Browser
        arguments:
            - '@anime_db.smotret_anime.browser.client'
            - '@anime_db.smotret_anime.browser.error_detector'
            - ~
            - ~
            - ~

    anime_db.smotret_anime.browser.error_detector:
        class: AnimeDb\Bundle\SmotretAnimeBrowserBundle\Service\ErrorDetector
        public: false

    anime_db.smotret_anime.browser.client:
        class: GuzzleHttp\Client
        public: false
